import { test, expect } from '@playwright/test'

test('test', async ({ page }) => {
  await page.goto('https://www.google.com/')
  await page.goto('http://localhost:4000/')
  await page.getByText('北海道').click()
  await page.getByText('青森県').click()
  await page.getByText('岩手県').click()
  await page.getByText('東京都').click()
  await page.getByText('新潟県').click()
  await page.getByText('和歌山県').click()
  await page.getByText('島根県').click()
  await page.getByText('広島県').click()
  await page.screenshot({ path: `test.png` })
  await page
    .locator('div')
    .filter({ hasText: /^青森県$/ })
    .getByRole('checkbox')
    .uncheck()
  await page.locator('label').filter({ hasText: '北海道' }).click()
  await page.locator('label').filter({ hasText: '岩手県' }).click()
  await page.locator('label').filter({ hasText: '東京都' }).click()
  await page.locator('label').filter({ hasText: '新潟県' }).click()
  await page.locator('label').filter({ hasText: '広島県' }).click()
  await page.locator('label').filter({ hasText: '島根県' }).click()
  await page.locator('label').filter({ hasText: '和歌山県' }).click()
  await page
    .locator('div')
    .filter({ hasText: /^山形県$/ })
    .getByRole('checkbox')
    .check()
  await page.getByText('福島県').click()
  await page.getByText('新潟県').click()
  await page
    .locator('div')
    .filter({ hasText: /^新潟県$/ })
    .getByRole('checkbox')
    .uncheck()
  await page
    .locator('div')
    .filter({ hasText: /^山形県$/ })
    .getByRole('checkbox')
    .uncheck()
  await page
    .locator('div')
    .filter({ hasText: /^福島県$/ })
    .getByRole('checkbox')
    .uncheck()
  await page
    .locator('div')
    .filter({ hasText: /^東京都$/ })
    .getByRole('checkbox')
    .check()
  await page
    .locator('div')
    .filter({ hasText: /^東京都$/ })
    .getByRole('checkbox')
    .uncheck()
  await page.getByText('神奈川県').click()
  await page.getByText('新潟県').click()
  await page
    .locator('div')
    .filter({ hasText: /^富山県$/ })
    .getByRole('checkbox')
    .check()
  await page
    .locator('div')
    .filter({ hasText: /^新潟県$/ })
    .getByRole('checkbox')
    .uncheck()
  await page
    .locator('div')
    .filter({ hasText: /^神奈川県$/ })
    .getByRole('checkbox')
    .uncheck()
  await page
    .locator('div')
    .filter({ hasText: /^富山県$/ })
    .getByRole('checkbox')
    .uncheck()
  await page.screenshot({ path: `test.png` })
})
